// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// PackageBasicInfo is an object. This represents the basic information about a package.
type PackageBasicInfo struct {
	// Id:
	Id string `json:"id" mapstructure:"id"`
	// IsMalicious:
	IsMalicious bool `json:"is_malicious,omitempty" mapstructure:"is_malicious,omitempty"`
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type" mapstructure:"package_type"`
	// PackageVersion:
	PackageVersion interface{} `json:"package_version" mapstructure:"package_version"`
	// Provenance:
	Provenance interface{} `json:"provenance,omitempty" mapstructure:"provenance,omitempty"`
	// RepoDescription:
	RepoDescription interface{} `json:"repo_description,omitempty" mapstructure:"repo_description,omitempty"`
	// Score:
	Score interface{} `json:"score,omitempty" mapstructure:"score,omitempty"`
}

// Validate implements basic validation for this model
func (m PackageBasicInfo) Validate() error {
	return validation.Errors{
		"id": validation.Validate(
			m.Id, validation.Required, is.UUID,
		),
		"packageType": validation.Validate(
			m.PackageType, validation.Required,
		),
	}.Filter()
}

// GetId returns the Id property
func (m PackageBasicInfo) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *PackageBasicInfo) SetId(val string) {
	m.Id = val
}

// GetIsMalicious returns the IsMalicious property
func (m PackageBasicInfo) GetIsMalicious() bool {
	return m.IsMalicious
}

// SetIsMalicious sets the IsMalicious property
func (m *PackageBasicInfo) SetIsMalicious(val bool) {
	m.IsMalicious = val
}

// GetPackageName returns the PackageName property
func (m PackageBasicInfo) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *PackageBasicInfo) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m PackageBasicInfo) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *PackageBasicInfo) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetPackageVersion returns the PackageVersion property
func (m PackageBasicInfo) GetPackageVersion() interface{} {
	return m.PackageVersion
}

// SetPackageVersion sets the PackageVersion property
func (m *PackageBasicInfo) SetPackageVersion(val interface{}) {
	m.PackageVersion = val
}

// GetProvenance returns the Provenance property
func (m PackageBasicInfo) GetProvenance() interface{} {
	return m.Provenance
}

// SetProvenance sets the Provenance property
func (m *PackageBasicInfo) SetProvenance(val interface{}) {
	m.Provenance = val
}

// GetRepoDescription returns the RepoDescription property
func (m PackageBasicInfo) GetRepoDescription() interface{} {
	return m.RepoDescription
}

// SetRepoDescription sets the RepoDescription property
func (m *PackageBasicInfo) SetRepoDescription(val interface{}) {
	m.RepoDescription = val
}

// GetScore returns the Score property
func (m PackageBasicInfo) GetScore() interface{} {
	return m.Score
}

// SetScore sets the Score property
func (m *PackageBasicInfo) SetScore(val interface{}) {
	m.Score = val
}
