// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters is an object.
type GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters struct {
	// NumVulnerabilities:
	NumVulnerabilities interface{} `json:"num_vulnerabilities,omitempty" mapstructure:"num_vulnerabilities,omitempty"`
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// PackageVersion:
	PackageVersion interface{} `json:"package_version,omitempty" mapstructure:"package_version,omitempty"`
	// Token:
	Token interface{} `json:"token,omitempty" mapstructure:"token,omitempty"`
}

// Validate implements basic validation for this model
func (m GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetNumVulnerabilities returns the NumVulnerabilities property
func (m GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) GetNumVulnerabilities() interface{} {
	return m.NumVulnerabilities
}

// SetNumVulnerabilities sets the NumVulnerabilities property
func (m *GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) SetNumVulnerabilities(val interface{}) {
	m.NumVulnerabilities = val
}

// GetPackageName returns the PackageName property
func (m GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetPackageVersion returns the PackageVersion property
func (m GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) GetPackageVersion() interface{} {
	return m.PackageVersion
}

// SetPackageVersion sets the PackageVersion property
func (m *GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) SetPackageVersion(val interface{}) {
	m.PackageVersion = val
}

// GetToken returns the Token property
func (m GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) GetToken() interface{} {
	return m.Token
}

// SetToken sets the Token property
func (m *GetVulnerabilitiesV2VulnerabilitiesGetQueryParameters) SetToken(val interface{}) {
	m.Token = val
}
