// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// DependencyResponse is an object.
type DependencyResponse struct {
	// Context:
	Context interface{} `json:"@context,omitempty" mapstructure:"@context,omitempty"`
	// Dependencies:
	Dependencies []Dependency `json:"dependencies" mapstructure:"dependencies"`
	// Summary:
	Summary DependenciesSummary `json:"summary" mapstructure:"summary"`
}

// Validate implements basic validation for this model
func (m DependencyResponse) Validate() error {
	return validation.Errors{
		"dependencies": validation.Validate(
			m.Dependencies, validation.NotNil,
		),
		"summary": validation.Validate(
			m.Summary,
		),
	}.Filter()
}

// GetContext returns the Context property
func (m DependencyResponse) GetContext() interface{} {
	return m.Context
}

// SetContext sets the Context property
func (m *DependencyResponse) SetContext(val interface{}) {
	m.Context = val
}

// GetDependencies returns the Dependencies property
func (m DependencyResponse) GetDependencies() []Dependency {
	return m.Dependencies
}

// SetDependencies sets the Dependencies property
func (m *DependencyResponse) SetDependencies(val []Dependency) {
	m.Dependencies = val
}

// GetSummary returns the Summary property
func (m DependencyResponse) GetSummary() DependenciesSummary {
	return m.Summary
}

// SetSummary sets the Summary property
func (m *DependencyResponse) SetSummary(val DependenciesSummary) {
	m.Summary = val
}
