// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetRepositoryReportQueryParameters is an object.
type V2GetRepositoryReportQueryParameters struct {
	// Name:
	Name string `json:"name" mapstructure:"name"`
}

// Validate implements basic validation for this model
func (m V2GetRepositoryReportQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetName returns the Name property
func (m V2GetRepositoryReportQueryParameters) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *V2GetRepositoryReportQueryParameters) SetName(val string) {
	m.Name = val
}
