// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetSimilarQueryParameters is an object.
type V2GetSimilarQueryParameters struct {
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// PackageVersion:
	PackageVersion interface{} `json:"package_version,omitempty" mapstructure:"package_version,omitempty"`
}

// Validate implements basic validation for this model
func (m V2GetSimilarQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetPackageName returns the PackageName property
func (m V2GetSimilarQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *V2GetSimilarQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m V2GetSimilarQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *V2GetSimilarQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetPackageVersion returns the PackageVersion property
func (m V2GetSimilarQueryParameters) GetPackageVersion() interface{} {
	return m.PackageVersion
}

// SetPackageVersion sets the PackageVersion property
func (m *V2GetSimilarQueryParameters) SetPackageVersion(val interface{}) {
	m.PackageVersion = val
}
