// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// License is an object. All the licence information about a package.
type License struct {
	// Claims:
	Claims []LicenseClaim `json:"claims,omitempty" mapstructure:"claims,omitempty"`
	// License:
	License interface{} `json:"license,omitempty" mapstructure:"license,omitempty"`
}

// Validate implements basic validation for this model
func (m License) Validate() error {
	return validation.Errors{
		"claims": validation.Validate(
			m.Claims,
		),
	}.Filter()
}

// GetClaims returns the Claims property
func (m License) GetClaims() []LicenseClaim {
	return m.Claims
}

// SetClaims sets the Claims property
func (m *License) SetClaims(val []LicenseClaim) {
	m.Claims = val
}

// GetLicense returns the License property
func (m License) GetLicense() interface{} {
	return m.License
}

// SetLicense sets the License property
func (m *License) SetLicense(val interface{}) {
	m.License = val
}
