// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// V2GetPackageQueryParameters is an object.
type V2GetPackageQueryParameters struct {
	// Id:
	Id string `json:"id" mapstructure:"id"`
}

// Validate implements basic validation for this model
func (m V2GetPackageQueryParameters) Validate() error {
	return validation.Errors{
		"id": validation.Validate(
			m.Id, validation.Required, is.UUID,
		),
	}.Filter()
}

// GetId returns the Id property
func (m V2GetPackageQueryParameters) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *V2GetPackageQueryParameters) SetId(val string) {
	m.Id = val
}
