// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetSameOriginQueryParameters is an object.
type V2GetSameOriginQueryParameters struct {
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// Token:
	Token string `json:"token,omitempty" mapstructure:"token,omitempty"`
}

// Validate implements basic validation for this model
func (m V2GetSameOriginQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetPackageName returns the PackageName property
func (m V2GetSameOriginQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *V2GetSameOriginQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m V2GetSameOriginQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *V2GetSameOriginQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetToken returns the Token property
func (m V2GetSameOriginQueryParameters) GetToken() string {
	return m.Token
}

// SetToken sets the Token property
func (m *V2GetSameOriginQueryParameters) SetToken(val string) {
	m.Token = val
}
