// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"time"
)

// PackageSummaryAnnotation is an object. This represents a package annotation.
type PackageSummaryAnnotation struct {
	// Description:
	Description interface{} `json:"description,omitempty" mapstructure:"description,omitempty"`
	// Score:
	Score interface{} `json:"score,omitempty" mapstructure:"score,omitempty"`
	// Status:
	Status SummaryAnnotationStatus `json:"status,omitempty" mapstructure:"status,omitempty"`
	// UpdatedAt:
	UpdatedAt time.Time `json:"updated_at" mapstructure:"updated_at"`
}

// Validate implements basic validation for this model
func (m PackageSummaryAnnotation) Validate() error {
	return validation.Errors{
		"status": validation.Validate(
			m.Status,
		),
		"updatedAt": validation.Validate(
			m.UpdatedAt, validation.Required, validation.Date(time.RFC3339),
		),
	}.Filter()
}

// GetDescription returns the Description property
func (m PackageSummaryAnnotation) GetDescription() interface{} {
	return m.Description
}

// SetDescription sets the Description property
func (m *PackageSummaryAnnotation) SetDescription(val interface{}) {
	m.Description = val
}

// GetScore returns the Score property
func (m PackageSummaryAnnotation) GetScore() interface{} {
	return m.Score
}

// SetScore sets the Score property
func (m *PackageSummaryAnnotation) SetScore(val interface{}) {
	m.Score = val
}

// GetStatus returns the Status property
func (m PackageSummaryAnnotation) GetStatus() SummaryAnnotationStatus {
	return m.Status
}

// SetStatus sets the Status property
func (m *PackageSummaryAnnotation) SetStatus(val SummaryAnnotationStatus) {
	m.Status = val
}

// GetUpdatedAt returns the UpdatedAt property
func (m PackageSummaryAnnotation) GetUpdatedAt() time.Time {
	return m.UpdatedAt
}

// SetUpdatedAt sets the UpdatedAt property
func (m *PackageSummaryAnnotation) SetUpdatedAt(val time.Time) {
	m.UpdatedAt = val
}
