// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetContributorReportQueryParameters is an object.
type V2GetContributorReportQueryParameters struct {
	// Login:
	Login string `json:"login" mapstructure:"login"`
}

// Validate implements basic validation for this model
func (m V2GetContributorReportQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetLogin returns the Login property
func (m V2GetContributorReportQueryParameters) GetLogin() string {
	return m.Login
}

// SetLogin sets the Login property
func (m *V2GetContributorReportQueryParameters) SetLogin(val string) {
	m.Login = val
}
