// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// TrustySummarizedPackageVersion is an object.
type TrustySummarizedPackageVersion struct {
	// Id:
	Id interface{} `json:"id,omitempty" mapstructure:"id,omitempty"`
	// IsDeprecated:
	IsDeprecated bool `json:"is_deprecated,omitempty" mapstructure:"is_deprecated,omitempty"`
	// Score:
	Score interface{} `json:"score" mapstructure:"score"`
	// Version:
	Version string `json:"version" mapstructure:"version"`
	// VersionDate:
	VersionDate interface{} `json:"version_date" mapstructure:"version_date"`
}

// Validate implements basic validation for this model
func (m TrustySummarizedPackageVersion) Validate() error {
	return validation.Errors{}.Filter()
}

// GetId returns the Id property
func (m TrustySummarizedPackageVersion) GetId() interface{} {
	return m.Id
}

// SetId sets the Id property
func (m *TrustySummarizedPackageVersion) SetId(val interface{}) {
	m.Id = val
}

// GetIsDeprecated returns the IsDeprecated property
func (m TrustySummarizedPackageVersion) GetIsDeprecated() bool {
	return m.IsDeprecated
}

// SetIsDeprecated sets the IsDeprecated property
func (m *TrustySummarizedPackageVersion) SetIsDeprecated(val bool) {
	m.IsDeprecated = val
}

// GetScore returns the Score property
func (m TrustySummarizedPackageVersion) GetScore() interface{} {
	return m.Score
}

// SetScore sets the Score property
func (m *TrustySummarizedPackageVersion) SetScore(val interface{}) {
	m.Score = val
}

// GetVersion returns the Version property
func (m TrustySummarizedPackageVersion) GetVersion() string {
	return m.Version
}

// SetVersion sets the Version property
func (m *TrustySummarizedPackageVersion) SetVersion(val string) {
	m.Version = val
}

// GetVersionDate returns the VersionDate property
func (m TrustySummarizedPackageVersion) GetVersionDate() interface{} {
	return m.VersionDate
}

// SetVersionDate sets the VersionDate property
func (m *TrustySummarizedPackageVersion) SetVersionDate(val interface{}) {
	m.VersionDate = val
}
