// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// GetVersionsV2VersionsGetQueryParameters is an object.
type GetVersionsV2VersionsGetQueryParameters struct {
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// Token:
	Token interface{} `json:"token,omitempty" mapstructure:"token,omitempty"`
	// VersionFragment:
	VersionFragment interface{} `json:"version_fragment,omitempty" mapstructure:"version_fragment,omitempty"`
	// VersionPrefix:
	VersionPrefix interface{} `json:"version_prefix,omitempty" mapstructure:"version_prefix,omitempty"`
}

// Validate implements basic validation for this model
func (m GetVersionsV2VersionsGetQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetPackageName returns the PackageName property
func (m GetVersionsV2VersionsGetQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *GetVersionsV2VersionsGetQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m GetVersionsV2VersionsGetQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *GetVersionsV2VersionsGetQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetToken returns the Token property
func (m GetVersionsV2VersionsGetQueryParameters) GetToken() interface{} {
	return m.Token
}

// SetToken sets the Token property
func (m *GetVersionsV2VersionsGetQueryParameters) SetToken(val interface{}) {
	m.Token = val
}

// GetVersionFragment returns the VersionFragment property
func (m GetVersionsV2VersionsGetQueryParameters) GetVersionFragment() interface{} {
	return m.VersionFragment
}

// SetVersionFragment sets the VersionFragment property
func (m *GetVersionsV2VersionsGetQueryParameters) SetVersionFragment(val interface{}) {
	m.VersionFragment = val
}

// GetVersionPrefix returns the VersionPrefix property
func (m GetVersionsV2VersionsGetQueryParameters) GetVersionPrefix() interface{} {
	return m.VersionPrefix
}

// SetVersionPrefix sets the VersionPrefix property
func (m *GetVersionsV2VersionsGetQueryParameters) SetVersionPrefix(val interface{}) {
	m.VersionPrefix = val
}
