// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// PackageMaliciousPayload is an object. This represents the payload details for a malicious package.
type PackageMaliciousPayload struct {
	// Details:
	Details interface{} `json:"details,omitempty" mapstructure:"details,omitempty"`
	// Modified:
	Modified interface{} `json:"modified,omitempty" mapstructure:"modified,omitempty"`
	// Published:
	Published interface{} `json:"published,omitempty" mapstructure:"published,omitempty"`
	// Source:
	Source interface{} `json:"source,omitempty" mapstructure:"source,omitempty"`
	// Summary:
	Summary string `json:"summary" mapstructure:"summary"`
}

// Validate implements basic validation for this model
func (m PackageMaliciousPayload) Validate() error {
	return validation.Errors{}.Filter()
}

// GetDetails returns the Details property
func (m PackageMaliciousPayload) GetDetails() interface{} {
	return m.Details
}

// SetDetails sets the Details property
func (m *PackageMaliciousPayload) SetDetails(val interface{}) {
	m.Details = val
}

// GetModified returns the Modified property
func (m PackageMaliciousPayload) GetModified() interface{} {
	return m.Modified
}

// SetModified sets the Modified property
func (m *PackageMaliciousPayload) SetModified(val interface{}) {
	m.Modified = val
}

// GetPublished returns the Published property
func (m PackageMaliciousPayload) GetPublished() interface{} {
	return m.Published
}

// SetPublished sets the Published property
func (m *PackageMaliciousPayload) SetPublished(val interface{}) {
	m.Published = val
}

// GetSource returns the Source property
func (m PackageMaliciousPayload) GetSource() interface{} {
	return m.Source
}

// SetSource sets the Source property
func (m *PackageMaliciousPayload) SetSource(val interface{}) {
	m.Source = val
}

// GetSummary returns the Summary property
func (m PackageMaliciousPayload) GetSummary() string {
	return m.Summary
}

// SetSummary sets the Summary property
func (m *PackageMaliciousPayload) SetSummary(val string) {
	m.Summary = val
}
