// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// TrustyPackageData is an object.
type TrustyPackageData struct {
	// Archived:
	Archived interface{} `json:"archived,omitempty" mapstructure:"archived,omitempty"`
	// Author:
	Author interface{} `json:"author,omitempty" mapstructure:"author,omitempty"`
	// AuthorEmail:
	AuthorEmail interface{} `json:"author_email,omitempty" mapstructure:"author_email,omitempty"`
	// ContributorCount:
	ContributorCount interface{} `json:"contributor_count,omitempty" mapstructure:"contributor_count,omitempty"`
	// Contributors:
	Contributors interface{} `json:"contributors,omitempty" mapstructure:"contributors,omitempty"`
	// DefaultBranch:
	DefaultBranch interface{} `json:"default_branch,omitempty" mapstructure:"default_branch,omitempty"`
	// Disabled:
	Disabled interface{} `json:"disabled,omitempty" mapstructure:"disabled,omitempty"`
	// Followers:
	Followers interface{} `json:"followers,omitempty" mapstructure:"followers,omitempty"`
	// Following:
	Following interface{} `json:"following,omitempty" mapstructure:"following,omitempty"`
	// ForksCount:
	ForksCount interface{} `json:"forks_count,omitempty" mapstructure:"forks_count,omitempty"`
	// HasDownloads:
	HasDownloads interface{} `json:"has_downloads,omitempty" mapstructure:"has_downloads,omitempty"`
	// HasIssues:
	HasIssues interface{} `json:"has_issues,omitempty" mapstructure:"has_issues,omitempty"`
	// HasProjects:
	HasProjects interface{} `json:"has_projects,omitempty" mapstructure:"has_projects,omitempty"`
	// HasTriggeredReingestion:
	HasTriggeredReingestion interface{} `json:"has_triggered_reingestion,omitempty" mapstructure:"has_triggered_reingestion,omitempty"`
	// HomePage:
	HomePage interface{} `json:"home_page,omitempty" mapstructure:"home_page,omitempty"`
	// Id:
	Id string `json:"id" mapstructure:"id"`
	// IsDeprecated:
	IsDeprecated interface{} `json:"is_deprecated,omitempty" mapstructure:"is_deprecated,omitempty"`
	// LastUpdate:
	LastUpdate interface{} `json:"last_update,omitempty" mapstructure:"last_update,omitempty"`
	// Malicious:
	Malicious interface{} `json:"malicious,omitempty" mapstructure:"malicious,omitempty"`
	// Name:
	Name string `json:"name" mapstructure:"name"`
	// OpenIssuesCount:
	OpenIssuesCount interface{} `json:"open_issues_count,omitempty" mapstructure:"open_issues_count,omitempty"`
	// Origin:
	Origin interface{} `json:"origin,omitempty" mapstructure:"origin,omitempty"`
	// Owner:
	Owner interface{} `json:"owner,omitempty" mapstructure:"owner,omitempty"`
	// PackageDescription:
	PackageDescription interface{} `json:"package_description,omitempty" mapstructure:"package_description,omitempty"`
	// PublicGists:
	PublicGists interface{} `json:"public_gists,omitempty" mapstructure:"public_gists,omitempty"`
	// PublicRepos:
	PublicRepos interface{} `json:"public_repos,omitempty" mapstructure:"public_repos,omitempty"`
	// RepoDescription:
	RepoDescription interface{} `json:"repo_description,omitempty" mapstructure:"repo_description,omitempty"`
	// RepositoryId:
	RepositoryId interface{} `json:"repository_id,omitempty" mapstructure:"repository_id,omitempty"`
	// RepositoryName:
	RepositoryName interface{} `json:"repository_name,omitempty" mapstructure:"repository_name,omitempty"`
	// Scores:
	Scores interface{} `json:"scores,omitempty" mapstructure:"scores,omitempty"`
	// StargazersCount:
	StargazersCount interface{} `json:"stargazers_count,omitempty" mapstructure:"stargazers_count,omitempty"`
	// Status:
	Status PackageStatus `json:"status" mapstructure:"status"`
	// StatusCode:
	StatusCode interface{} `json:"status_code,omitempty" mapstructure:"status_code,omitempty"`
	// Type:
	Type PackageType `json:"type" mapstructure:"type"`
	// Version:
	Version interface{} `json:"version,omitempty" mapstructure:"version,omitempty"`
	// VersionDate:
	VersionDate interface{} `json:"version_date,omitempty" mapstructure:"version_date,omitempty"`
	// Visibility:
	Visibility interface{} `json:"visibility,omitempty" mapstructure:"visibility,omitempty"`
	// WatchersCount:
	WatchersCount interface{} `json:"watchers_count,omitempty" mapstructure:"watchers_count,omitempty"`
}

// Validate implements basic validation for this model
func (m TrustyPackageData) Validate() error {
	return validation.Errors{
		"id": validation.Validate(
			m.Id, validation.Required, is.UUID,
		),
		"status": validation.Validate(
			m.Status, validation.Required,
		),
		"type": validation.Validate(
			m.Type, validation.Required,
		),
	}.Filter()
}

// GetArchived returns the Archived property
func (m TrustyPackageData) GetArchived() interface{} {
	return m.Archived
}

// SetArchived sets the Archived property
func (m *TrustyPackageData) SetArchived(val interface{}) {
	m.Archived = val
}

// GetAuthor returns the Author property
func (m TrustyPackageData) GetAuthor() interface{} {
	return m.Author
}

// SetAuthor sets the Author property
func (m *TrustyPackageData) SetAuthor(val interface{}) {
	m.Author = val
}

// GetAuthorEmail returns the AuthorEmail property
func (m TrustyPackageData) GetAuthorEmail() interface{} {
	return m.AuthorEmail
}

// SetAuthorEmail sets the AuthorEmail property
func (m *TrustyPackageData) SetAuthorEmail(val interface{}) {
	m.AuthorEmail = val
}

// GetContributorCount returns the ContributorCount property
func (m TrustyPackageData) GetContributorCount() interface{} {
	return m.ContributorCount
}

// SetContributorCount sets the ContributorCount property
func (m *TrustyPackageData) SetContributorCount(val interface{}) {
	m.ContributorCount = val
}

// GetContributors returns the Contributors property
func (m TrustyPackageData) GetContributors() interface{} {
	return m.Contributors
}

// SetContributors sets the Contributors property
func (m *TrustyPackageData) SetContributors(val interface{}) {
	m.Contributors = val
}

// GetDefaultBranch returns the DefaultBranch property
func (m TrustyPackageData) GetDefaultBranch() interface{} {
	return m.DefaultBranch
}

// SetDefaultBranch sets the DefaultBranch property
func (m *TrustyPackageData) SetDefaultBranch(val interface{}) {
	m.DefaultBranch = val
}

// GetDisabled returns the Disabled property
func (m TrustyPackageData) GetDisabled() interface{} {
	return m.Disabled
}

// SetDisabled sets the Disabled property
func (m *TrustyPackageData) SetDisabled(val interface{}) {
	m.Disabled = val
}

// GetFollowers returns the Followers property
func (m TrustyPackageData) GetFollowers() interface{} {
	return m.Followers
}

// SetFollowers sets the Followers property
func (m *TrustyPackageData) SetFollowers(val interface{}) {
	m.Followers = val
}

// GetFollowing returns the Following property
func (m TrustyPackageData) GetFollowing() interface{} {
	return m.Following
}

// SetFollowing sets the Following property
func (m *TrustyPackageData) SetFollowing(val interface{}) {
	m.Following = val
}

// GetForksCount returns the ForksCount property
func (m TrustyPackageData) GetForksCount() interface{} {
	return m.ForksCount
}

// SetForksCount sets the ForksCount property
func (m *TrustyPackageData) SetForksCount(val interface{}) {
	m.ForksCount = val
}

// GetHasDownloads returns the HasDownloads property
func (m TrustyPackageData) GetHasDownloads() interface{} {
	return m.HasDownloads
}

// SetHasDownloads sets the HasDownloads property
func (m *TrustyPackageData) SetHasDownloads(val interface{}) {
	m.HasDownloads = val
}

// GetHasIssues returns the HasIssues property
func (m TrustyPackageData) GetHasIssues() interface{} {
	return m.HasIssues
}

// SetHasIssues sets the HasIssues property
func (m *TrustyPackageData) SetHasIssues(val interface{}) {
	m.HasIssues = val
}

// GetHasProjects returns the HasProjects property
func (m TrustyPackageData) GetHasProjects() interface{} {
	return m.HasProjects
}

// SetHasProjects sets the HasProjects property
func (m *TrustyPackageData) SetHasProjects(val interface{}) {
	m.HasProjects = val
}

// GetHasTriggeredReingestion returns the HasTriggeredReingestion property
func (m TrustyPackageData) GetHasTriggeredReingestion() interface{} {
	return m.HasTriggeredReingestion
}

// SetHasTriggeredReingestion sets the HasTriggeredReingestion property
func (m *TrustyPackageData) SetHasTriggeredReingestion(val interface{}) {
	m.HasTriggeredReingestion = val
}

// GetHomePage returns the HomePage property
func (m TrustyPackageData) GetHomePage() interface{} {
	return m.HomePage
}

// SetHomePage sets the HomePage property
func (m *TrustyPackageData) SetHomePage(val interface{}) {
	m.HomePage = val
}

// GetId returns the Id property
func (m TrustyPackageData) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *TrustyPackageData) SetId(val string) {
	m.Id = val
}

// GetIsDeprecated returns the IsDeprecated property
func (m TrustyPackageData) GetIsDeprecated() interface{} {
	return m.IsDeprecated
}

// SetIsDeprecated sets the IsDeprecated property
func (m *TrustyPackageData) SetIsDeprecated(val interface{}) {
	m.IsDeprecated = val
}

// GetLastUpdate returns the LastUpdate property
func (m TrustyPackageData) GetLastUpdate() interface{} {
	return m.LastUpdate
}

// SetLastUpdate sets the LastUpdate property
func (m *TrustyPackageData) SetLastUpdate(val interface{}) {
	m.LastUpdate = val
}

// GetMalicious returns the Malicious property
func (m TrustyPackageData) GetMalicious() interface{} {
	return m.Malicious
}

// SetMalicious sets the Malicious property
func (m *TrustyPackageData) SetMalicious(val interface{}) {
	m.Malicious = val
}

// GetName returns the Name property
func (m TrustyPackageData) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *TrustyPackageData) SetName(val string) {
	m.Name = val
}

// GetOpenIssuesCount returns the OpenIssuesCount property
func (m TrustyPackageData) GetOpenIssuesCount() interface{} {
	return m.OpenIssuesCount
}

// SetOpenIssuesCount sets the OpenIssuesCount property
func (m *TrustyPackageData) SetOpenIssuesCount(val interface{}) {
	m.OpenIssuesCount = val
}

// GetOrigin returns the Origin property
func (m TrustyPackageData) GetOrigin() interface{} {
	return m.Origin
}

// SetOrigin sets the Origin property
func (m *TrustyPackageData) SetOrigin(val interface{}) {
	m.Origin = val
}

// GetOwner returns the Owner property
func (m TrustyPackageData) GetOwner() interface{} {
	return m.Owner
}

// SetOwner sets the Owner property
func (m *TrustyPackageData) SetOwner(val interface{}) {
	m.Owner = val
}

// GetPackageDescription returns the PackageDescription property
func (m TrustyPackageData) GetPackageDescription() interface{} {
	return m.PackageDescription
}

// SetPackageDescription sets the PackageDescription property
func (m *TrustyPackageData) SetPackageDescription(val interface{}) {
	m.PackageDescription = val
}

// GetPublicGists returns the PublicGists property
func (m TrustyPackageData) GetPublicGists() interface{} {
	return m.PublicGists
}

// SetPublicGists sets the PublicGists property
func (m *TrustyPackageData) SetPublicGists(val interface{}) {
	m.PublicGists = val
}

// GetPublicRepos returns the PublicRepos property
func (m TrustyPackageData) GetPublicRepos() interface{} {
	return m.PublicRepos
}

// SetPublicRepos sets the PublicRepos property
func (m *TrustyPackageData) SetPublicRepos(val interface{}) {
	m.PublicRepos = val
}

// GetRepoDescription returns the RepoDescription property
func (m TrustyPackageData) GetRepoDescription() interface{} {
	return m.RepoDescription
}

// SetRepoDescription sets the RepoDescription property
func (m *TrustyPackageData) SetRepoDescription(val interface{}) {
	m.RepoDescription = val
}

// GetRepositoryId returns the RepositoryId property
func (m TrustyPackageData) GetRepositoryId() interface{} {
	return m.RepositoryId
}

// SetRepositoryId sets the RepositoryId property
func (m *TrustyPackageData) SetRepositoryId(val interface{}) {
	m.RepositoryId = val
}

// GetRepositoryName returns the RepositoryName property
func (m TrustyPackageData) GetRepositoryName() interface{} {
	return m.RepositoryName
}

// SetRepositoryName sets the RepositoryName property
func (m *TrustyPackageData) SetRepositoryName(val interface{}) {
	m.RepositoryName = val
}

// GetScores returns the Scores property
func (m TrustyPackageData) GetScores() interface{} {
	return m.Scores
}

// SetScores sets the Scores property
func (m *TrustyPackageData) SetScores(val interface{}) {
	m.Scores = val
}

// GetStargazersCount returns the StargazersCount property
func (m TrustyPackageData) GetStargazersCount() interface{} {
	return m.StargazersCount
}

// SetStargazersCount sets the StargazersCount property
func (m *TrustyPackageData) SetStargazersCount(val interface{}) {
	m.StargazersCount = val
}

// GetStatus returns the Status property
func (m TrustyPackageData) GetStatus() PackageStatus {
	return m.Status
}

// SetStatus sets the Status property
func (m *TrustyPackageData) SetStatus(val PackageStatus) {
	m.Status = val
}

// GetStatusCode returns the StatusCode property
func (m TrustyPackageData) GetStatusCode() interface{} {
	return m.StatusCode
}

// SetStatusCode sets the StatusCode property
func (m *TrustyPackageData) SetStatusCode(val interface{}) {
	m.StatusCode = val
}

// GetType returns the Type property
func (m TrustyPackageData) GetType() PackageType {
	return m.Type
}

// SetType sets the Type property
func (m *TrustyPackageData) SetType(val PackageType) {
	m.Type = val
}

// GetVersion returns the Version property
func (m TrustyPackageData) GetVersion() interface{} {
	return m.Version
}

// SetVersion sets the Version property
func (m *TrustyPackageData) SetVersion(val interface{}) {
	m.Version = val
}

// GetVersionDate returns the VersionDate property
func (m TrustyPackageData) GetVersionDate() interface{} {
	return m.VersionDate
}

// SetVersionDate sets the VersionDate property
func (m *TrustyPackageData) SetVersionDate(val interface{}) {
	m.VersionDate = val
}

// GetVisibility returns the Visibility property
func (m TrustyPackageData) GetVisibility() interface{} {
	return m.Visibility
}

// SetVisibility sets the Visibility property
func (m *TrustyPackageData) SetVisibility(val interface{}) {
	m.Visibility = val
}

// GetWatchersCount returns the WatchersCount property
func (m TrustyPackageData) GetWatchersCount() interface{} {
	return m.WatchersCount
}

// SetWatchersCount sets the WatchersCount property
func (m *TrustyPackageData) SetWatchersCount(val interface{}) {
	m.WatchersCount = val
}
