// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// V2GetDependenciesIdQueryParameters is an object.
type V2GetDependenciesIdQueryParameters struct {
	// Filter:
	Filter interface{} `json:"filter,omitempty" mapstructure:"filter,omitempty"`
	// Id:
	Id string `json:"id" mapstructure:"id"`
	// PageFrom:
	PageFrom int32 `json:"page_from,omitempty" mapstructure:"page_from,omitempty"`
	// PageTo:
	PageTo int32 `json:"page_to,omitempty" mapstructure:"page_to,omitempty"`
	// RecurseLimit:
	RecurseLimit int32 `json:"recurse_limit,omitempty" mapstructure:"recurse_limit,omitempty"`
	// SortBy:
	SortBy interface{} `json:"sort_by,omitempty" mapstructure:"sort_by,omitempty"`
	// SortOrder:
	SortOrder interface{} `json:"sort_order,omitempty" mapstructure:"sort_order,omitempty"`
}

// Validate implements basic validation for this model
func (m V2GetDependenciesIdQueryParameters) Validate() error {
	return validation.Errors{
		"id": validation.Validate(
			m.Id, validation.Required, is.UUID,
		),
	}.Filter()
}

// GetFilter returns the Filter property
func (m V2GetDependenciesIdQueryParameters) GetFilter() interface{} {
	return m.Filter
}

// SetFilter sets the Filter property
func (m *V2GetDependenciesIdQueryParameters) SetFilter(val interface{}) {
	m.Filter = val
}

// GetId returns the Id property
func (m V2GetDependenciesIdQueryParameters) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *V2GetDependenciesIdQueryParameters) SetId(val string) {
	m.Id = val
}

// GetPageFrom returns the PageFrom property
func (m V2GetDependenciesIdQueryParameters) GetPageFrom() int32 {
	return m.PageFrom
}

// SetPageFrom sets the PageFrom property
func (m *V2GetDependenciesIdQueryParameters) SetPageFrom(val int32) {
	m.PageFrom = val
}

// GetPageTo returns the PageTo property
func (m V2GetDependenciesIdQueryParameters) GetPageTo() int32 {
	return m.PageTo
}

// SetPageTo sets the PageTo property
func (m *V2GetDependenciesIdQueryParameters) SetPageTo(val int32) {
	m.PageTo = val
}

// GetRecurseLimit returns the RecurseLimit property
func (m V2GetDependenciesIdQueryParameters) GetRecurseLimit() int32 {
	return m.RecurseLimit
}

// SetRecurseLimit sets the RecurseLimit property
func (m *V2GetDependenciesIdQueryParameters) SetRecurseLimit(val int32) {
	m.RecurseLimit = val
}

// GetSortBy returns the SortBy property
func (m V2GetDependenciesIdQueryParameters) GetSortBy() interface{} {
	return m.SortBy
}

// SetSortBy sets the SortBy property
func (m *V2GetDependenciesIdQueryParameters) SetSortBy(val interface{}) {
	m.SortBy = val
}

// GetSortOrder returns the SortOrder property
func (m V2GetDependenciesIdQueryParameters) GetSortOrder() interface{} {
	return m.SortOrder
}

// SetSortOrder sets the SortOrder property
func (m *V2GetDependenciesIdQueryParameters) SetSortOrder(val interface{}) {
	m.SortOrder = val
}
