// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetSummaryQueryParameters is an object.
type V2GetSummaryQueryParameters struct {
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// PackageVersion:
	PackageVersion interface{} `json:"package_version,omitempty" mapstructure:"package_version,omitempty"`
}

// Validate implements basic validation for this model
func (m V2GetSummaryQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetPackageName returns the PackageName property
func (m V2GetSummaryQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *V2GetSummaryQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m V2GetSummaryQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *V2GetSummaryQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetPackageVersion returns the PackageVersion property
func (m V2GetSummaryQueryParameters) GetPackageVersion() interface{} {
	return m.PackageVersion
}

// SetPackageVersion sets the PackageVersion property
func (m *V2GetSummaryQueryParameters) SetPackageVersion(val interface{}) {
	m.PackageVersion = val
}
