// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// LicenseClaim is an object. A claim about a license.
type LicenseClaim struct {
	// Claim:
	Claim interface{} `json:"claim,omitempty" mapstructure:"claim,omitempty"`
	// Content:
	Content interface{} `json:"content,omitempty" mapstructure:"content,omitempty"`
	// Description:
	Description interface{} `json:"description,omitempty" mapstructure:"description,omitempty"`
	// Id:
	Id string `json:"id,omitempty" mapstructure:"id,omitempty"`
	// Licenses:
	Licenses []string `json:"licenses,omitempty" mapstructure:"licenses,omitempty"`
	// OwnerId:
	OwnerId string `json:"owner_id,omitempty" mapstructure:"owner_id,omitempty"`
	// Source:
	Source interface{} `json:"source,omitempty" mapstructure:"source,omitempty"`
	// Url:
	Url interface{} `json:"url,omitempty" mapstructure:"url,omitempty"`
}

// Validate implements basic validation for this model
func (m LicenseClaim) Validate() error {
	return validation.Errors{
		"id": validation.Validate(
			m.Id, is.UUID,
		),
		"licenses": validation.Validate(
			m.Licenses,
		),
		"ownerId": validation.Validate(
			m.OwnerId, is.UUID,
		),
	}.Filter()
}

// GetClaim returns the Claim property
func (m LicenseClaim) GetClaim() interface{} {
	return m.Claim
}

// SetClaim sets the Claim property
func (m *LicenseClaim) SetClaim(val interface{}) {
	m.Claim = val
}

// GetContent returns the Content property
func (m LicenseClaim) GetContent() interface{} {
	return m.Content
}

// SetContent sets the Content property
func (m *LicenseClaim) SetContent(val interface{}) {
	m.Content = val
}

// GetDescription returns the Description property
func (m LicenseClaim) GetDescription() interface{} {
	return m.Description
}

// SetDescription sets the Description property
func (m *LicenseClaim) SetDescription(val interface{}) {
	m.Description = val
}

// GetId returns the Id property
func (m LicenseClaim) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *LicenseClaim) SetId(val string) {
	m.Id = val
}

// GetLicenses returns the Licenses property
func (m LicenseClaim) GetLicenses() []string {
	return m.Licenses
}

// SetLicenses sets the Licenses property
func (m *LicenseClaim) SetLicenses(val []string) {
	m.Licenses = val
}

// GetOwnerId returns the OwnerId property
func (m LicenseClaim) GetOwnerId() string {
	return m.OwnerId
}

// SetOwnerId sets the OwnerId property
func (m *LicenseClaim) SetOwnerId(val string) {
	m.OwnerId = val
}

// GetSource returns the Source property
func (m LicenseClaim) GetSource() interface{} {
	return m.Source
}

// SetSource sets the Source property
func (m *LicenseClaim) SetSource(val interface{}) {
	m.Source = val
}

// GetUrl returns the Url property
func (m LicenseClaim) GetUrl() interface{} {
	return m.Url
}

// SetUrl sets the Url property
func (m *LicenseClaim) SetUrl(val interface{}) {
	m.Url = val
}
