// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetPackageProvenanceQueryParameters is an object.
type V2GetPackageProvenanceQueryParameters struct {
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// PackageVersion:
	PackageVersion interface{} `json:"package_version,omitempty" mapstructure:"package_version,omitempty"`
	// PeriodCount:
	PeriodCount int32 `json:"period_count,omitempty" mapstructure:"period_count,omitempty"`
	// PeriodType:
	PeriodType string `json:"period_type,omitempty" mapstructure:"period_type,omitempty"`
}

// Validate implements basic validation for this model
func (m V2GetPackageProvenanceQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetPackageName returns the PackageName property
func (m V2GetPackageProvenanceQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *V2GetPackageProvenanceQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m V2GetPackageProvenanceQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *V2GetPackageProvenanceQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetPackageVersion returns the PackageVersion property
func (m V2GetPackageProvenanceQueryParameters) GetPackageVersion() interface{} {
	return m.PackageVersion
}

// SetPackageVersion sets the PackageVersion property
func (m *V2GetPackageProvenanceQueryParameters) SetPackageVersion(val interface{}) {
	m.PackageVersion = val
}

// GetPeriodCount returns the PeriodCount property
func (m V2GetPackageProvenanceQueryParameters) GetPeriodCount() int32 {
	return m.PeriodCount
}

// SetPeriodCount sets the PeriodCount property
func (m *V2GetPackageProvenanceQueryParameters) SetPeriodCount(val int32) {
	m.PeriodCount = val
}

// GetPeriodType returns the PeriodType property
func (m V2GetPackageProvenanceQueryParameters) GetPeriodType() string {
	return m.PeriodType
}

// SetPeriodType sets the PeriodType property
func (m *V2GetPackageProvenanceQueryParameters) SetPeriodType(val string) {
	m.PeriodType = val
}
