// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// Dependency is an object.
type Dependency struct {
	// ActivityScore:
	ActivityScore interface{} `json:"activity_score,omitempty" mapstructure:"activity_score,omitempty"`
	// DeclaredLicense:
	DeclaredLicense interface{} `json:"declared_license,omitempty" mapstructure:"declared_license,omitempty"`
	// Depths:
	Depths []int32 `json:"depths" mapstructure:"depths"`
	// MalOsvId:
	MalOsvId interface{} `json:"mal_osv_id,omitempty" mapstructure:"mal_osv_id,omitempty"`
	// Name:
	Name string `json:"name" mapstructure:"name"`
	// PackageId:
	PackageId string `json:"package_id" mapstructure:"package_id"`
	// Parents:
	Parents []string `json:"parents" mapstructure:"parents"`
	// Paths:
	Paths [][]string `json:"paths,omitempty" mapstructure:"paths,omitempty"`
	// Type:
	Type string `json:"type" mapstructure:"type"`
	// VersionId:
	VersionId string `json:"version_id" mapstructure:"version_id"`
	// VersionName:
	VersionName string `json:"version_name" mapstructure:"version_name"`
	// VulnSeverity:
	VulnSeverity interface{} `json:"vuln_severity,omitempty" mapstructure:"vuln_severity,omitempty"`
}

// Validate implements basic validation for this model
func (m Dependency) Validate() error {
	return validation.Errors{
		"depths": validation.Validate(
			m.Depths, validation.NotNil,
		),
		"packageId": validation.Validate(
			m.PackageId, validation.Required, is.UUID,
		),
		"parents": validation.Validate(
			m.Parents, validation.NotNil,
		),
		"paths": validation.Validate(
			m.Paths,
		),
		"versionId": validation.Validate(
			m.VersionId, validation.Required, is.UUID,
		),
	}.Filter()
}

// GetActivityScore returns the ActivityScore property
func (m Dependency) GetActivityScore() interface{} {
	return m.ActivityScore
}

// SetActivityScore sets the ActivityScore property
func (m *Dependency) SetActivityScore(val interface{}) {
	m.ActivityScore = val
}

// GetDeclaredLicense returns the DeclaredLicense property
func (m Dependency) GetDeclaredLicense() interface{} {
	return m.DeclaredLicense
}

// SetDeclaredLicense sets the DeclaredLicense property
func (m *Dependency) SetDeclaredLicense(val interface{}) {
	m.DeclaredLicense = val
}

// GetDepths returns the Depths property
func (m Dependency) GetDepths() []int32 {
	return m.Depths
}

// SetDepths sets the Depths property
func (m *Dependency) SetDepths(val []int32) {
	m.Depths = val
}

// GetMalOsvId returns the MalOsvId property
func (m Dependency) GetMalOsvId() interface{} {
	return m.MalOsvId
}

// SetMalOsvId sets the MalOsvId property
func (m *Dependency) SetMalOsvId(val interface{}) {
	m.MalOsvId = val
}

// GetName returns the Name property
func (m Dependency) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *Dependency) SetName(val string) {
	m.Name = val
}

// GetPackageId returns the PackageId property
func (m Dependency) GetPackageId() string {
	return m.PackageId
}

// SetPackageId sets the PackageId property
func (m *Dependency) SetPackageId(val string) {
	m.PackageId = val
}

// GetParents returns the Parents property
func (m Dependency) GetParents() []string {
	return m.Parents
}

// SetParents sets the Parents property
func (m *Dependency) SetParents(val []string) {
	m.Parents = val
}

// GetPaths returns the Paths property
func (m Dependency) GetPaths() [][]string {
	return m.Paths
}

// SetPaths sets the Paths property
func (m *Dependency) SetPaths(val [][]string) {
	m.Paths = val
}

// GetType returns the Type property
func (m Dependency) GetType() string {
	return m.Type
}

// SetType sets the Type property
func (m *Dependency) SetType(val string) {
	m.Type = val
}

// GetVersionId returns the VersionId property
func (m Dependency) GetVersionId() string {
	return m.VersionId
}

// SetVersionId sets the VersionId property
func (m *Dependency) SetVersionId(val string) {
	m.VersionId = val
}

// GetVersionName returns the VersionName property
func (m Dependency) GetVersionName() string {
	return m.VersionName
}

// SetVersionName sets the VersionName property
func (m *Dependency) SetVersionName(val string) {
	m.VersionName = val
}

// GetVulnSeverity returns the VulnSeverity property
func (m Dependency) GetVulnSeverity() interface{} {
	return m.VulnSeverity
}

// SetVulnSeverity sets the VulnSeverity property
func (m *Dependency) SetVulnSeverity(val interface{}) {
	m.VulnSeverity = val
}
