// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// AlternativesStatus is an enum.
type AlternativesStatus string

// Validate implements basic validation for this model
func (m AlternativesStatus) Validate() error {
	return InKnownAlternativesStatus.Validate(m)
}

var (
	AlternativesStatusComplete   AlternativesStatus = "complete"
	AlternativesStatusInProgress AlternativesStatus = "in_progress"

	// KnownAlternativesStatus is the list of valid AlternativesStatus
	KnownAlternativesStatus = []AlternativesStatus{
		AlternativesStatusComplete,
		AlternativesStatusInProgress,
	}
	// KnownAlternativesStatusString is the list of valid AlternativesStatus as string
	KnownAlternativesStatusString = []string{
		string(AlternativesStatusComplete),
		string(AlternativesStatusInProgress),
	}

	// InKnownAlternativesStatus is an ozzo-validator for AlternativesStatus
	InKnownAlternativesStatus = validation.In(
		AlternativesStatusComplete,
		AlternativesStatusInProgress,
	)
)
