// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// SummaryAnnotationStatus is an enum.
type SummaryAnnotationStatus string

// Validate implements basic validation for this model
func (m SummaryAnnotationStatus) Validate() error {
	return InKnownSummaryAnnotationStatus.Validate(m)
}

var (
	SummaryAnnotationStatusComplete   SummaryAnnotationStatus = "complete"
	SummaryAnnotationStatusInProgress SummaryAnnotationStatus = "in_progress"

	// KnownSummaryAnnotationStatus is the list of valid SummaryAnnotationStatus
	KnownSummaryAnnotationStatus = []SummaryAnnotationStatus{
		SummaryAnnotationStatusComplete,
		SummaryAnnotationStatusInProgress,
	}
	// KnownSummaryAnnotationStatusString is the list of valid SummaryAnnotationStatus as string
	KnownSummaryAnnotationStatusString = []string{
		string(SummaryAnnotationStatusComplete),
		string(SummaryAnnotationStatusInProgress),
	}

	// InKnownSummaryAnnotationStatus is an ozzo-validator for SummaryAnnotationStatus
	InKnownSummaryAnnotationStatus = validation.In(
		SummaryAnnotationStatusComplete,
		SummaryAnnotationStatusInProgress,
	)
)
