// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// HistoricalProvenanceOT is an object.
type HistoricalProvenanceOT struct {
	// HpOverTime:
	HpOverTime map[string]PeriodHistoricalProvenance `json:"hp_over_time,omitempty" mapstructure:"hp_over_time,omitempty"`
	// PeriodCount:
	PeriodCount int32 `json:"period_count,omitempty" mapstructure:"period_count,omitempty"`
	// PeriodType:
	PeriodType string `json:"period_type,omitempty" mapstructure:"period_type,omitempty"`
}

// Validate implements basic validation for this model
func (m HistoricalProvenanceOT) Validate() error {
	return validation.Errors{
		"hpOverTime": validation.Validate(
			m.HpOverTime,
		),
	}.Filter()
}

// GetHpOverTime returns the HpOverTime property
func (m HistoricalProvenanceOT) GetHpOverTime() map[string]PeriodHistoricalProvenance {
	return m.HpOverTime
}

// SetHpOverTime sets the HpOverTime property
func (m *HistoricalProvenanceOT) SetHpOverTime(val map[string]PeriodHistoricalProvenance) {
	m.HpOverTime = val
}

// GetPeriodCount returns the PeriodCount property
func (m HistoricalProvenanceOT) GetPeriodCount() int32 {
	return m.PeriodCount
}

// SetPeriodCount sets the PeriodCount property
func (m *HistoricalProvenanceOT) SetPeriodCount(val int32) {
	m.PeriodCount = val
}

// GetPeriodType returns the PeriodType property
func (m HistoricalProvenanceOT) GetPeriodType() string {
	return m.PeriodType
}

// SetPeriodType sets the PeriodType property
func (m *HistoricalProvenanceOT) SetPeriodType(val string) {
	m.PeriodType = val
}
