// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// PackageAlternatives is an object.
type PackageAlternatives struct {
	// Packages:
	Packages interface{} `json:"packages,omitempty" mapstructure:"packages,omitempty"`
	// Status:
	Status AlternativesStatus `json:"status,omitempty" mapstructure:"status,omitempty"`
}

// Validate implements basic validation for this model
func (m PackageAlternatives) Validate() error {
	return validation.Errors{
		"status": validation.Validate(
			m.Status,
		),
	}.Filter()
}

// GetPackages returns the Packages property
func (m PackageAlternatives) GetPackages() interface{} {
	return m.Packages
}

// SetPackages sets the Packages property
func (m *PackageAlternatives) SetPackages(val interface{}) {
	m.Packages = val
}

// GetStatus returns the Status property
func (m PackageAlternatives) GetStatus() AlternativesStatus {
	return m.Status
}

// SetStatus sets the Status property
func (m *PackageAlternatives) SetStatus(val AlternativesStatus) {
	m.Status = val
}
