// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// HTTPValidationError is an object.
type HTTPValidationError struct {
	// Detail:
	Detail []ValidationError `json:"detail,omitempty" mapstructure:"detail,omitempty"`
}

// Validate implements basic validation for this model
func (m HTTPValidationError) Validate() error {
	return validation.Errors{
		"detail": validation.Validate(
			m.Detail,
		),
	}.Filter()
}

// GetDetail returns the Detail property
func (m HTTPValidationError) GetDetail() []ValidationError {
	return m.Detail
}

// SetDetail sets the Detail property
func (m *HTTPValidationError) SetDetail(val []ValidationError) {
	m.Detail = val
}
