// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ValidationError is an object.
type ValidationError struct {
	// Loc:
	Loc []interface{} `json:"loc" mapstructure:"loc"`
	// Msg:
	Msg string `json:"msg" mapstructure:"msg"`
	// Type:
	Type string `json:"type" mapstructure:"type"`
}

// Validate implements basic validation for this model
func (m ValidationError) Validate() error {
	return validation.Errors{
		"loc": validation.Validate(
			m.Loc, validation.NotNil,
		),
	}.Filter()
}

// GetLoc returns the Loc property
func (m ValidationError) GetLoc() []interface{} {
	return m.Loc
}

// SetLoc sets the Loc property
func (m *ValidationError) SetLoc(val []interface{}) {
	m.Loc = val
}

// GetMsg returns the Msg property
func (m ValidationError) GetMsg() string {
	return m.Msg
}

// SetMsg sets the Msg property
func (m *ValidationError) SetMsg(val string) {
	m.Msg = val
}

// GetType returns the Type property
func (m ValidationError) GetType() string {
	return m.Type
}

// SetType sets the Type property
func (m *ValidationError) SetType(val string) {
	m.Type = val
}
