// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// PackageContributorData is an object.
type PackageContributorData struct {
	// Author:
	Author interface{} `json:"author,omitempty" mapstructure:"author,omitempty"`
	// AuthorEmail:
	AuthorEmail interface{} `json:"author_email,omitempty" mapstructure:"author_email,omitempty"`
	// AvatarUrl:
	AvatarUrl interface{} `json:"avatar_url,omitempty" mapstructure:"avatar_url,omitempty"`
	// Blog:
	Blog interface{} `json:"blog,omitempty" mapstructure:"blog,omitempty"`
	// Company:
	Company interface{} `json:"company,omitempty" mapstructure:"company,omitempty"`
	// Email:
	Email interface{} `json:"email,omitempty" mapstructure:"email,omitempty"`
	// Followers:
	Followers interface{} `json:"followers,omitempty" mapstructure:"followers,omitempty"`
	// Following:
	Following interface{} `json:"following,omitempty" mapstructure:"following,omitempty"`
	// GravatarId:
	GravatarId interface{} `json:"gravatar_id,omitempty" mapstructure:"gravatar_id,omitempty"`
	// Hireable:
	Hireable interface{} `json:"hireable,omitempty" mapstructure:"hireable,omitempty"`
	// HtmlUrl:
	HtmlUrl interface{} `json:"html_url,omitempty" mapstructure:"html_url,omitempty"`
	// Id:
	Id string `json:"id" mapstructure:"id"`
	// Location:
	Location interface{} `json:"location,omitempty" mapstructure:"location,omitempty"`
	// Login:
	Login interface{} `json:"login,omitempty" mapstructure:"login,omitempty"`
	// PublicGists:
	PublicGists interface{} `json:"public_gists,omitempty" mapstructure:"public_gists,omitempty"`
	// PublicRepos:
	PublicRepos interface{} `json:"public_repos,omitempty" mapstructure:"public_repos,omitempty"`
	// Scores:
	Scores interface{} `json:"scores,omitempty" mapstructure:"scores,omitempty"`
	// TwitterUsername:
	TwitterUsername interface{} `json:"twitter_username,omitempty" mapstructure:"twitter_username,omitempty"`
	// Url:
	Url interface{} `json:"url,omitempty" mapstructure:"url,omitempty"`
}

// Validate implements basic validation for this model
func (m PackageContributorData) Validate() error {
	return validation.Errors{
		"id": validation.Validate(
			m.Id, validation.Required, is.UUID,
		),
	}.Filter()
}

// GetAuthor returns the Author property
func (m PackageContributorData) GetAuthor() interface{} {
	return m.Author
}

// SetAuthor sets the Author property
func (m *PackageContributorData) SetAuthor(val interface{}) {
	m.Author = val
}

// GetAuthorEmail returns the AuthorEmail property
func (m PackageContributorData) GetAuthorEmail() interface{} {
	return m.AuthorEmail
}

// SetAuthorEmail sets the AuthorEmail property
func (m *PackageContributorData) SetAuthorEmail(val interface{}) {
	m.AuthorEmail = val
}

// GetAvatarUrl returns the AvatarUrl property
func (m PackageContributorData) GetAvatarUrl() interface{} {
	return m.AvatarUrl
}

// SetAvatarUrl sets the AvatarUrl property
func (m *PackageContributorData) SetAvatarUrl(val interface{}) {
	m.AvatarUrl = val
}

// GetBlog returns the Blog property
func (m PackageContributorData) GetBlog() interface{} {
	return m.Blog
}

// SetBlog sets the Blog property
func (m *PackageContributorData) SetBlog(val interface{}) {
	m.Blog = val
}

// GetCompany returns the Company property
func (m PackageContributorData) GetCompany() interface{} {
	return m.Company
}

// SetCompany sets the Company property
func (m *PackageContributorData) SetCompany(val interface{}) {
	m.Company = val
}

// GetEmail returns the Email property
func (m PackageContributorData) GetEmail() interface{} {
	return m.Email
}

// SetEmail sets the Email property
func (m *PackageContributorData) SetEmail(val interface{}) {
	m.Email = val
}

// GetFollowers returns the Followers property
func (m PackageContributorData) GetFollowers() interface{} {
	return m.Followers
}

// SetFollowers sets the Followers property
func (m *PackageContributorData) SetFollowers(val interface{}) {
	m.Followers = val
}

// GetFollowing returns the Following property
func (m PackageContributorData) GetFollowing() interface{} {
	return m.Following
}

// SetFollowing sets the Following property
func (m *PackageContributorData) SetFollowing(val interface{}) {
	m.Following = val
}

// GetGravatarId returns the GravatarId property
func (m PackageContributorData) GetGravatarId() interface{} {
	return m.GravatarId
}

// SetGravatarId sets the GravatarId property
func (m *PackageContributorData) SetGravatarId(val interface{}) {
	m.GravatarId = val
}

// GetHireable returns the Hireable property
func (m PackageContributorData) GetHireable() interface{} {
	return m.Hireable
}

// SetHireable sets the Hireable property
func (m *PackageContributorData) SetHireable(val interface{}) {
	m.Hireable = val
}

// GetHtmlUrl returns the HtmlUrl property
func (m PackageContributorData) GetHtmlUrl() interface{} {
	return m.HtmlUrl
}

// SetHtmlUrl sets the HtmlUrl property
func (m *PackageContributorData) SetHtmlUrl(val interface{}) {
	m.HtmlUrl = val
}

// GetId returns the Id property
func (m PackageContributorData) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *PackageContributorData) SetId(val string) {
	m.Id = val
}

// GetLocation returns the Location property
func (m PackageContributorData) GetLocation() interface{} {
	return m.Location
}

// SetLocation sets the Location property
func (m *PackageContributorData) SetLocation(val interface{}) {
	m.Location = val
}

// GetLogin returns the Login property
func (m PackageContributorData) GetLogin() interface{} {
	return m.Login
}

// SetLogin sets the Login property
func (m *PackageContributorData) SetLogin(val interface{}) {
	m.Login = val
}

// GetPublicGists returns the PublicGists property
func (m PackageContributorData) GetPublicGists() interface{} {
	return m.PublicGists
}

// SetPublicGists sets the PublicGists property
func (m *PackageContributorData) SetPublicGists(val interface{}) {
	m.PublicGists = val
}

// GetPublicRepos returns the PublicRepos property
func (m PackageContributorData) GetPublicRepos() interface{} {
	return m.PublicRepos
}

// SetPublicRepos sets the PublicRepos property
func (m *PackageContributorData) SetPublicRepos(val interface{}) {
	m.PublicRepos = val
}

// GetScores returns the Scores property
func (m PackageContributorData) GetScores() interface{} {
	return m.Scores
}

// SetScores sets the Scores property
func (m *PackageContributorData) SetScores(val interface{}) {
	m.Scores = val
}

// GetTwitterUsername returns the TwitterUsername property
func (m PackageContributorData) GetTwitterUsername() interface{} {
	return m.TwitterUsername
}

// SetTwitterUsername sets the TwitterUsername property
func (m *PackageContributorData) SetTwitterUsername(val interface{}) {
	m.TwitterUsername = val
}

// GetUrl returns the Url property
func (m PackageContributorData) GetUrl() interface{} {
	return m.Url
}

// SetUrl sets the Url property
func (m *PackageContributorData) SetUrl(val interface{}) {
	m.Url = val
}
