// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// PeriodHistoricalProvenance is an object.
type PeriodHistoricalProvenance struct {
	// Matches:
	Matches int32 `json:"matches,omitempty" mapstructure:"matches,omitempty"`
	// Tags:
	Tags int32 `json:"tags,omitempty" mapstructure:"tags,omitempty"`
	// Vers:
	Vers int32 `json:"vers,omitempty" mapstructure:"vers,omitempty"`
}

// Validate implements basic validation for this model
func (m PeriodHistoricalProvenance) Validate() error {
	return validation.Errors{}.Filter()
}

// GetMatches returns the Matches property
func (m PeriodHistoricalProvenance) GetMatches() int32 {
	return m.Matches
}

// SetMatches sets the Matches property
func (m *PeriodHistoricalProvenance) SetMatches(val int32) {
	m.Matches = val
}

// GetTags returns the Tags property
func (m PeriodHistoricalProvenance) GetTags() int32 {
	return m.Tags
}

// SetTags sets the Tags property
func (m *PeriodHistoricalProvenance) SetTags(val int32) {
	m.Tags = val
}

// GetVers returns the Vers property
func (m PeriodHistoricalProvenance) GetVers() int32 {
	return m.Vers
}

// SetVers sets the Vers property
func (m *PeriodHistoricalProvenance) SetVers(val int32) {
	m.Vers = val
}
