// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// PackageType is an enum.
type PackageType string

// Validate implements basic validation for this model
func (m PackageType) Validate() error {
	return InKnownPackageType.Validate(m)
}

var (
	PackageTypeCrates PackageType = "crates"
	PackageTypeGo     PackageType = "go"
	PackageTypeMaven  PackageType = "maven"
	PackageTypeNpm    PackageType = "npm"
	PackageTypePypi   PackageType = "pypi"

	// KnownPackageType is the list of valid PackageType
	KnownPackageType = []PackageType{
		PackageTypeCrates,
		PackageTypeGo,
		PackageTypeMaven,
		PackageTypeNpm,
		PackageTypePypi,
	}
	// KnownPackageTypeString is the list of valid PackageType as string
	KnownPackageTypeString = []string{
		string(PackageTypeCrates),
		string(PackageTypeGo),
		string(PackageTypeMaven),
		string(PackageTypeNpm),
		string(PackageTypePypi),
	}

	// InKnownPackageType is an ozzo-validator for PackageType
	InKnownPackageType = validation.In(
		PackageTypeCrates,
		PackageTypeGo,
		PackageTypeMaven,
		PackageTypeNpm,
		PackageTypePypi,
	)
)
