// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Trusty API
//	Version: v2
package api

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// V2GetDependenciesQueryParameters is an object.
type V2GetDependenciesQueryParameters struct {
	// Filter:
	Filter interface{} `json:"filter,omitempty" mapstructure:"filter,omitempty"`
	// PackageName:
	PackageName string `json:"package_name" mapstructure:"package_name"`
	// PackageType:
	PackageType PackageType `json:"package_type,omitempty" mapstructure:"package_type,omitempty"`
	// PackageVersion:
	PackageVersion interface{} `json:"package_version,omitempty" mapstructure:"package_version,omitempty"`
	// PageFrom:
	PageFrom int32 `json:"page_from,omitempty" mapstructure:"page_from,omitempty"`
	// PageTo:
	PageTo int32 `json:"page_to,omitempty" mapstructure:"page_to,omitempty"`
	// RecurseLimit:
	RecurseLimit int32 `json:"recurse_limit,omitempty" mapstructure:"recurse_limit,omitempty"`
	// SortBy:
	SortBy interface{} `json:"sort_by,omitempty" mapstructure:"sort_by,omitempty"`
	// SortOrder:
	SortOrder interface{} `json:"sort_order,omitempty" mapstructure:"sort_order,omitempty"`
}

// Validate implements basic validation for this model
func (m V2GetDependenciesQueryParameters) Validate() error {
	return validation.Errors{
		"packageType": validation.Validate(
			m.PackageType,
		),
	}.Filter()
}

// GetFilter returns the Filter property
func (m V2GetDependenciesQueryParameters) GetFilter() interface{} {
	return m.Filter
}

// SetFilter sets the Filter property
func (m *V2GetDependenciesQueryParameters) SetFilter(val interface{}) {
	m.Filter = val
}

// GetPackageName returns the PackageName property
func (m V2GetDependenciesQueryParameters) GetPackageName() string {
	return m.PackageName
}

// SetPackageName sets the PackageName property
func (m *V2GetDependenciesQueryParameters) SetPackageName(val string) {
	m.PackageName = val
}

// GetPackageType returns the PackageType property
func (m V2GetDependenciesQueryParameters) GetPackageType() PackageType {
	return m.PackageType
}

// SetPackageType sets the PackageType property
func (m *V2GetDependenciesQueryParameters) SetPackageType(val PackageType) {
	m.PackageType = val
}

// GetPackageVersion returns the PackageVersion property
func (m V2GetDependenciesQueryParameters) GetPackageVersion() interface{} {
	return m.PackageVersion
}

// SetPackageVersion sets the PackageVersion property
func (m *V2GetDependenciesQueryParameters) SetPackageVersion(val interface{}) {
	m.PackageVersion = val
}

// GetPageFrom returns the PageFrom property
func (m V2GetDependenciesQueryParameters) GetPageFrom() int32 {
	return m.PageFrom
}

// SetPageFrom sets the PageFrom property
func (m *V2GetDependenciesQueryParameters) SetPageFrom(val int32) {
	m.PageFrom = val
}

// GetPageTo returns the PageTo property
func (m V2GetDependenciesQueryParameters) GetPageTo() int32 {
	return m.PageTo
}

// SetPageTo sets the PageTo property
func (m *V2GetDependenciesQueryParameters) SetPageTo(val int32) {
	m.PageTo = val
}

// GetRecurseLimit returns the RecurseLimit property
func (m V2GetDependenciesQueryParameters) GetRecurseLimit() int32 {
	return m.RecurseLimit
}

// SetRecurseLimit sets the RecurseLimit property
func (m *V2GetDependenciesQueryParameters) SetRecurseLimit(val int32) {
	m.RecurseLimit = val
}

// GetSortBy returns the SortBy property
func (m V2GetDependenciesQueryParameters) GetSortBy() interface{} {
	return m.SortBy
}

// SetSortBy sets the SortBy property
func (m *V2GetDependenciesQueryParameters) SetSortBy(val interface{}) {
	m.SortBy = val
}

// GetSortOrder returns the SortOrder property
func (m V2GetDependenciesQueryParameters) GetSortOrder() interface{} {
	return m.SortOrder
}

// SetSortOrder sets the SortOrder property
func (m *V2GetDependenciesQueryParameters) SetSortOrder(val interface{}) {
	m.SortOrder = val
}
