/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// VulnerabilitiesAPIService VulnerabilitiesAPI service
type VulnerabilitiesAPIService service

type ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest struct {
	ctx context.Context
	ApiService *VulnerabilitiesAPIService
	packageName *string
	packageType *PackageType
	packageVersion *string
	token *string
	numVulnerabilities *int32
}

func (r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) PackageName(packageName string) ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest {
	r.packageName = &packageName
	return r
}

func (r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) PackageType(packageType PackageType) ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest {
	r.packageType = &packageType
	return r
}

func (r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) PackageVersion(packageVersion string) ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest {
	r.packageVersion = &packageVersion
	return r
}

func (r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) Token(token string) ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest {
	r.token = &token
	return r
}

func (r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) NumVulnerabilities(numVulnerabilities int32) ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest {
	r.numVulnerabilities = &numVulnerabilities
	return r
}

func (r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) Execute() (*VulnerabilityListResponse, *http.Response, error) {
	return r.ApiService.GetVulnerabilitiesV2VulnerabilitiesGetExecute(r)
}

/*
GetVulnerabilitiesV2VulnerabilitiesGet Get Vulnerabilities

Fetch a list of vulnerabilities for all versions of a package.
If a version is provided, only the vulnerabilities for that specific version are returned.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest
*/
func (a *VulnerabilitiesAPIService) GetVulnerabilitiesV2VulnerabilitiesGet(ctx context.Context) ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest {
	return ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return VulnerabilityListResponse
func (a *VulnerabilitiesAPIService) GetVulnerabilitiesV2VulnerabilitiesGetExecute(r ApiGetVulnerabilitiesV2VulnerabilitiesGetRequest) (*VulnerabilityListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *VulnerabilityListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VulnerabilitiesAPIService.GetVulnerabilitiesV2VulnerabilitiesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v2/vulnerabilities"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.packageName == nil {
		return localVarReturnValue, nil, reportError("packageName is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "package_name", r.packageName, "form", "")
	if r.packageType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "package_type", r.packageType, "form", "")
	}
	if r.packageVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "package_version", r.packageVersion, "form", "")
	}
	if r.token != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "token", r.token, "form", "")
	}
	if r.numVulnerabilities != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "num_vulnerabilities", r.numVulnerabilities, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetVulnerabilityV2VulnerabilityGetRequest struct {
	ctx context.Context
	ApiService *VulnerabilitiesAPIService
	osvId *string
}

func (r ApiGetVulnerabilityV2VulnerabilityGetRequest) OsvId(osvId string) ApiGetVulnerabilityV2VulnerabilityGetRequest {
	r.osvId = &osvId
	return r
}

func (r ApiGetVulnerabilityV2VulnerabilityGetRequest) Execute() (*VulnerabilityResponse, *http.Response, error) {
	return r.ApiService.GetVulnerabilityV2VulnerabilityGetExecute(r)
}

/*
GetVulnerabilityV2VulnerabilityGet Get Vulnerability

Fetch the data for a vulnerability.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetVulnerabilityV2VulnerabilityGetRequest
*/
func (a *VulnerabilitiesAPIService) GetVulnerabilityV2VulnerabilityGet(ctx context.Context) ApiGetVulnerabilityV2VulnerabilityGetRequest {
	return ApiGetVulnerabilityV2VulnerabilityGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return VulnerabilityResponse
func (a *VulnerabilitiesAPIService) GetVulnerabilityV2VulnerabilityGetExecute(r ApiGetVulnerabilityV2VulnerabilityGetRequest) (*VulnerabilityResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *VulnerabilityResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VulnerabilitiesAPIService.GetVulnerabilityV2VulnerabilityGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v2/vulnerability"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.osvId == nil {
		return localVarReturnValue, nil, reportError("osvId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "osv_id", r.osvId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
