/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// Scores struct for Scores
type Scores struct {
	PersonAnnotation *PersonAnnotation
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Scores) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into PersonAnnotation
	err = json.Unmarshal(data, &dst.PersonAnnotation);
	if err == nil {
		jsonPersonAnnotation, _ := json.Marshal(dst.PersonAnnotation)
		if string(jsonPersonAnnotation) == "{}" { // empty struct
			dst.PersonAnnotation = nil
		} else {
			return nil // data stored in dst.PersonAnnotation, return on the first match
		}
	} else {
		dst.PersonAnnotation = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Scores)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Scores) MarshalJSON() ([]byte, error) {
	if src.PersonAnnotation != nil {
		return json.Marshal(&src.PersonAnnotation)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableScores struct {
	value *Scores
	isSet bool
}

func (v NullableScores) Get() *Scores {
	return v.value
}

func (v *NullableScores) Set(val *Scores) {
	v.value = val
	v.isSet = true
}

func (v NullableScores) IsSet() bool {
	return v.isSet
}

func (v *NullableScores) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScores(val *Scores) *NullableScores {
	return &NullableScores{value: val, isSet: true}
}

func (v NullableScores) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScores) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


