/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// Scores2 struct for Scores2
type Scores2 struct {
	PackageAnnotation *PackageAnnotation
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Scores2) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into PackageAnnotation
	err = json.Unmarshal(data, &dst.PackageAnnotation);
	if err == nil {
		jsonPackageAnnotation, _ := json.Marshal(dst.PackageAnnotation)
		if string(jsonPackageAnnotation) == "{}" { // empty struct
			dst.PackageAnnotation = nil
		} else {
			return nil // data stored in dst.PackageAnnotation, return on the first match
		}
	} else {
		dst.PackageAnnotation = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Scores2)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Scores2) MarshalJSON() ([]byte, error) {
	if src.PackageAnnotation != nil {
		return json.Marshal(&src.PackageAnnotation)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableScores2 struct {
	value *Scores2
	isSet bool
}

func (v NullableScores2) Get() *Scores2 {
	return v.value
}

func (v *NullableScores2) Set(val *Scores2) {
	v.value = val
	v.isSet = true
}

func (v NullableScores2) IsSet() bool {
	return v.isSet
}

func (v *NullableScores2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScores2(val *Scores2) *NullableScores2 {
	return &NullableScores2{value: val, isSet: true}
}

func (v NullableScores2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScores2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


