/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// Sigstore struct for Sigstore
type Sigstore struct {
	ProvenanceData *ProvenanceData
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Sigstore) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ProvenanceData
	err = json.Unmarshal(data, &dst.ProvenanceData);
	if err == nil {
		jsonProvenanceData, _ := json.Marshal(dst.ProvenanceData)
		if string(jsonProvenanceData) == "{}" { // empty struct
			dst.ProvenanceData = nil
		} else {
			return nil // data stored in dst.ProvenanceData, return on the first match
		}
	} else {
		dst.ProvenanceData = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Sigstore)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Sigstore) MarshalJSON() ([]byte, error) {
	if src.ProvenanceData != nil {
		return json.Marshal(&src.ProvenanceData)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSigstore struct {
	value *Sigstore
	isSet bool
}

func (v NullableSigstore) Get() *Sigstore {
	return v.value
}

func (v *NullableSigstore) Set(val *Sigstore) {
	v.value = val
	v.isSet = true
}

func (v NullableSigstore) IsSet() bool {
	return v.isSet
}

func (v *NullableSigstore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSigstore(val *Sigstore) *NullableSigstore {
	return &NullableSigstore{value: val, isSet: true}
}

func (v NullableSigstore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSigstore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


