/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// OverTime struct for OverTime
type OverTime struct {
	HistoricalProvenanceOT *HistoricalProvenanceOT
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *OverTime) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into HistoricalProvenanceOT
	err = json.Unmarshal(data, &dst.HistoricalProvenanceOT);
	if err == nil {
		jsonHistoricalProvenanceOT, _ := json.Marshal(dst.HistoricalProvenanceOT)
		if string(jsonHistoricalProvenanceOT) == "{}" { // empty struct
			dst.HistoricalProvenanceOT = nil
		} else {
			return nil // data stored in dst.HistoricalProvenanceOT, return on the first match
		}
	} else {
		dst.HistoricalProvenanceOT = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(OverTime)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *OverTime) MarshalJSON() ([]byte, error) {
	if src.HistoricalProvenanceOT != nil {
		return json.Marshal(&src.HistoricalProvenanceOT)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableOverTime struct {
	value *OverTime
	isSet bool
}

func (v NullableOverTime) Get() *OverTime {
	return v.value
}

func (v *NullableOverTime) Set(val *OverTime) {
	v.value = val
	v.isSet = true
}

func (v NullableOverTime) IsSet() bool {
	return v.isSet
}

func (v *NullableOverTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverTime(val *OverTime) *NullableOverTime {
	return &NullableOverTime{value: val, isSet: true}
}

func (v NullableOverTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


