/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// Provenance struct for Provenance
type Provenance struct {
	PackageAnnotation *PackageAnnotation
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Provenance) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into PackageAnnotation
	err = json.Unmarshal(data, &dst.PackageAnnotation);
	if err == nil {
		jsonPackageAnnotation, _ := json.Marshal(dst.PackageAnnotation)
		if string(jsonPackageAnnotation) == "{}" { // empty struct
			dst.PackageAnnotation = nil
		} else {
			return nil // data stored in dst.PackageAnnotation, return on the first match
		}
	} else {
		dst.PackageAnnotation = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Provenance)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Provenance) MarshalJSON() ([]byte, error) {
	if src.PackageAnnotation != nil {
		return json.Marshal(&src.PackageAnnotation)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableProvenance struct {
	value *Provenance
	isSet bool
}

func (v NullableProvenance) Get() *Provenance {
	return v.value
}

func (v *NullableProvenance) Set(val *Provenance) {
	v.value = val
	v.isSet = true
}

func (v NullableProvenance) IsSet() bool {
	return v.isSet
}

func (v *NullableProvenance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvenance(val *Provenance) *NullableProvenance {
	return &NullableProvenance{value: val, isSet: true}
}

func (v NullableProvenance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvenance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


