/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// Scores1 struct for Scores1
type Scores1 struct {
	RepositoryAnnotation *RepositoryAnnotation
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Scores1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into RepositoryAnnotation
	err = json.Unmarshal(data, &dst.RepositoryAnnotation);
	if err == nil {
		jsonRepositoryAnnotation, _ := json.Marshal(dst.RepositoryAnnotation)
		if string(jsonRepositoryAnnotation) == "{}" { // empty struct
			dst.RepositoryAnnotation = nil
		} else {
			return nil // data stored in dst.RepositoryAnnotation, return on the first match
		}
	} else {
		dst.RepositoryAnnotation = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Scores1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Scores1) MarshalJSON() ([]byte, error) {
	if src.RepositoryAnnotation != nil {
		return json.Marshal(&src.RepositoryAnnotation)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableScores1 struct {
	value *Scores1
	isSet bool
}

func (v NullableScores1) Get() *Scores1 {
	return v.value
}

func (v *NullableScores1) Set(val *Scores1) {
	v.value = val
	v.isSet = true
}

func (v NullableScores1) IsSet() bool {
	return v.isSet
}

func (v *NullableScores1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScores1(val *Scores1) *NullableScores1 {
	return &NullableScores1{value: val, isSet: true}
}

func (v NullableScores1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScores1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


