/*
Trusty API

Trusty API

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SummaryAnnotationStatus the model 'SummaryAnnotationStatus'
type SummaryAnnotationStatus string

// List of SummaryAnnotationStatus
const (
	IN_PROGRESS SummaryAnnotationStatus = "in_progress"
	COMPLETE SummaryAnnotationStatus = "complete"
)

// All allowed values of SummaryAnnotationStatus enum
var AllowedSummaryAnnotationStatusEnumValues = []SummaryAnnotationStatus{
	"in_progress",
	"complete",
}

func (v *SummaryAnnotationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SummaryAnnotationStatus(value)
	for _, existing := range AllowedSummaryAnnotationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SummaryAnnotationStatus", value)
}

// NewSummaryAnnotationStatusFromValue returns a pointer to a valid SummaryAnnotationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSummaryAnnotationStatusFromValue(v string) (*SummaryAnnotationStatus, error) {
	ev := SummaryAnnotationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SummaryAnnotationStatus: valid values are %v", v, AllowedSummaryAnnotationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SummaryAnnotationStatus) IsValid() bool {
	for _, existing := range AllowedSummaryAnnotationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SummaryAnnotationStatus value
func (v SummaryAnnotationStatus) Ptr() *SummaryAnnotationStatus {
	return &v
}

type NullableSummaryAnnotationStatus struct {
	value *SummaryAnnotationStatus
	isSet bool
}

func (v NullableSummaryAnnotationStatus) Get() *SummaryAnnotationStatus {
	return v.value
}

func (v *NullableSummaryAnnotationStatus) Set(val *SummaryAnnotationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryAnnotationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryAnnotationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryAnnotationStatus(val *SummaryAnnotationStatus) *NullableSummaryAnnotationStatus {
	return &NullableSummaryAnnotationStatus{value: val, isSet: true}
}

func (v NullableSummaryAnnotationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryAnnotationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

