# Copyright 2024 Stacklok, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases 

    steps:
      - name: Set tag name
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v3
        with:
          go-version: '1.22'
          check-latest: true
  
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 1
      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@2f8b9ec22aedc9ce15039b6c7716aa6c2907df1c # v0.2.0
      - name: Generate SBOM
        shell: bash
        run: |
          bom generate --format=json -o /tmp/trusty-sdk-go-$TAG.spdx.json .
      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@2f8b9ec22aedc9ce15039b6c7716aa6c2907df1c # v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assets: "/tmp/trusty-sdk-go-$TAG.spdx.json"
          sbom: false
