---
name: Test

on:
  pull_request:

jobs:
  call-trusty:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Call trusty
        run: |
          # First we request the JWT id-token
          curl -v -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"

          tok=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

          # call trusty
          curl -v -H "Authorization: bearer $tok" \
              https://gh.trustypkg.dev/v1/report?package_name=uvicorn&package_type=pypi